### ISSUE TITLE
About FPS

### ISSUE THREAD

**Issue by aaahuia** [Seanseattle/MobileFaceSwap#15]
I run it on 3090 but the FPS can't reach 25fps
Am I missing some details?
Looking forward to your response

**Comment by beyonehan** [comment]
> I run it on 3090 but the FPS can't reach 25fps Am I missing some details? Looking forward to your response

Hi, could you tell me your FPS on 3090?

**Comment by aaahuia** [comment]
> > I run it on 3090 but the FPS can't reach 25fps Am I missing some details? Looking forward to your response
> 
> Hi, could you tell me your FPS on 3090?

As shown below, the processing speed of each image is between 0.15 seconds and 0.2 seconds

python time_check.py --target_video_path 10s_mobilefaceswap.mp4 --source_img_path /mnt/mfs/wangdonghui/data/1.jpg --use_gpu True
W1019 11:25:16.988435 15542 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W1019 11:25:17.036190 15542 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
input mean and std: 127.5 127.5
find model: ./checkpoints/landmarks/glintr100.onnx recognition
find model: ./checkpoints/landmarks/scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
/mnt/mfs/wangdonghui/MobileFaceSwap/utils/align_face.py:30: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  A, res, rank, s = np.linalg.lstsq(src_pts_, dst_pts_)
W1019 11:26:06.712710 15542 gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.2, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
  0%|                                                                                                                      | 0/250 [00:00<?, ?it/s]
0.22238469123840332
  0%|▍                                                                                                             | 1/250 [00:01<07:06,  1.71s/it]
0.18510675430297852
  1%|▉                                                                                                             | 2/250 [00:02<03:37,  1.14it/s]
0.18127012252807617
  1%|█▎                                                                                                            | 3/250 [00:02<02:26,  1.68it/s]
0.19201445579528809
  2%|█▊                                                                                                            | 4/250 [00:02<02:08,  1.92it/s]
0.15575170516967773
  2%|██▏                                                                                                           | 5/250 [00:03<02:20,  1.75it/s]
0.17618131637573242
  2%|██▋                                                                                                           | 6/250 [00:03<01:53,  2.15it/s]
0.18538236618041992
  3%|███                                                                                                           | 7/250 [00:03<01:37,  2.50it/s]
0.1773383617401123
  3%|███▌                                                                                                          | 8/250 [00:04<01:40,  2.42it/s]
0.1560380458831787
  4%|███▉                                                                                                          | 9/250 [00:05<02:35,  1.55it/s]
0.14922428131103516
  4%|████▎                                                                                                        | 10/250 [00:05<02:04,  1.93it/s]
0.15995073318481445
  4%|████▊                                                                                                        | 11/250 [00:06<01:57,  2.04it/s]
0.14891815185546875
  5%|█████▏                                                                                                       | 12/250 [00:06<01:37,  2.44it/s]
0.14820241928100586
  5%|█████▋                                                                                                       | 13/250 [00:07<02:21,  1.68it/s]
0.1681513786315918
  6%|██████                                                                                                       | 14/250 [00:07<02:03,  1.92it/s]
0.1500542163848877
  6%|██████▌                                                                                                      | 15/250 [00:08<01:45,  2.22it/s]
0.14726758003234863
  6%|██████▉                                                                                                      | 16/250 [00:08<01:36,  2.42it/s]
0.14962410926818848
  7%|███████▍                                                                                                     | 17/250 [00:08<01:48,  2.14it/s]
0.15721940994262695
  7%|███████▊                                                                                                     | 18/250 [00:09<01:31,  2.53it/s]
0.1529240608215332
  7%|███████▊                                                                                                     | 18/250 [00:10<02:19,  1.67it/s]
Traceback (most recent call last):
  File "time_check.py", line 96, in <module>
    video_test(args)
  File "time_check.py", line 73, in video_test
    cv2.imwrite('{}/out.jpg'.format(args.output_path), frame)
KeyboardInterrupt


Is it a problem with my environment? This is a new environment, the speed can reach 10FPS in the old environment, I think this should be one of the problems affecting the inference speed

**Comment by Luochangjiang10** [comment]
My test inference model on A100 only gets 17fps at most, am I doing something wrong?
![image](https://github.com/Seanseattle/MobileFaceSwap/assets/97878507/bee7349f-9564-40d9-82f1-3e0f83d9d215)

**Comment by rainq22** [comment]
hello，where is the time_check.py？
