### ISSUE TITLE
assert 'detection' in self.models when running `image_test.py`

### ISSUE THREAD

**Issue by eldare** [Seanseattle/MobileFaceSwap#18]
Hi, I'm experiencing the following error below.

I'm on MacOS 12.6

I've installed the following:
```
python 3.9
numpy==1.23.4
opencv-python==4.6.0.66
insightface==0.2.1
paddlepaddle==2.1.2
onnxruntime==1.13.1  // had to install because the image_test.py threw an error saying it was required
```

I've extracted `checkpoints.tar` in the root dir of the repo.

And I'm getting the following error:
```
$ python3.9 ./image_test.py --target_img_path ./content/input/target1.png --source_img_path ./content/input/source1.png --output_dir ./content/output/
/usr/local/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/usr/local/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/usr/local/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/usr/local/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/usr/local/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/usr/local/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "/Users/ME/MobileFaceSwap/./image_test.py", line 98, in <module>
    landmarkModel = LandmarkModel(name='landmarks')
  File "/Users/ME/MobileFaceSwap/utils/prepare_data.py", line 25, in __init__
    assert 'detection' in self.models
AssertionError
```

Any help would be really appreciated.
Thank you.

**Comment by eldare** [comment]
terribly sorry. checkpoints.tar failed in repo's root. it works great now. thank you.
